/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardTicketsIndexRouteImport } from './routes/_dashboard/tickets/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/_dashboard/notifications/index'
import { Route as DashboardBugsIndexRouteImport } from './routes/_dashboard/bugs/index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard/agents/index'
import { Route as DashboardAccountsIndexRouteImport } from './routes/_dashboard/accounts/index'
import { Route as DashboardMembersIndexRouteImport } from './routes/_dashboard/members/index'
import { Route as DashboardBugsBugIdRouteImport } from './routes/_dashboard/bugs/$bugId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBugsIndexRoute = DashboardBugsIndexRouteImport.update({
  id: '/bugs/',
  path: '/bugs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountsIndexRoute = DashboardAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBugsBugIdRoute = DashboardBugsBugIdRouteImport.update({
  id: '/bugs/$bugId',
  path: '/bugs/$bugId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/bugs/$bugId': typeof DashboardBugsBugIdRoute
  '/accounts/': typeof DashboardAccountsIndexRoute
  '/agents/': typeof DashboardAgentsIndexRoute
  '/bugs/': typeof DashboardBugsIndexRoute
  '/members/': typeof DashboardMembersIndexRoute
  '/notifications/': typeof DashboardNotificationsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/bugs/$bugId': typeof DashboardBugsBugIdRoute
  '/accounts': typeof DashboardAccountsIndexRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/bugs': typeof DashboardBugsIndexRoute
  '/members': typeof DashboardMembersIndexRoute
  '/notifications': typeof DashboardNotificationsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/tickets': typeof DashboardTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/bugs/$bugId': typeof DashboardBugsBugIdRoute
  '/_dashboard/accounts/': typeof DashboardAccountsIndexRoute
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/bugs/': typeof DashboardBugsIndexRoute
  '/_dashboard/members/': typeof DashboardMembersIndexRoute
  '/_dashboard/notifications/': typeof DashboardNotificationsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/tickets/': typeof DashboardTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bugs/$bugId'
    | '/accounts/'
    | '/agents/'
    | '/bugs/'
    | '/members/'
    | '/notifications/'
    | '/settings/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bugs/$bugId'
    | '/accounts'
    | '/agents'
    | '/bugs'
    | '/members'
    | '/notifications'
    | '/settings'
    | '/tickets'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_dashboard/'
    | '/_dashboard/bugs/$bugId'
    | '/_dashboard/accounts/'
    | '/_dashboard/agents/'
    | '/_dashboard/bugs/'
    | '/_dashboard/members/'
    | '/_dashboard/notifications/'
    | '/_dashboard/settings/'
    | '/_dashboard/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/tickets/': {
      id: '/_dashboard/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/notifications/': {
      id: '/_dashboard/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/bugs/': {
      id: '/_dashboard/bugs/'
      path: '/bugs'
      fullPath: '/bugs/'
      preLoaderRoute: typeof DashboardBugsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/accounts/': {
      id: '/_dashboard/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof DashboardAccountsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/members/': {
      id: '/_dashboard/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/bugs/$bugId': {
      id: '/_dashboard/bugs/$bugId'
      path: '/bugs/$bugId'
      fullPath: '/bugs/$bugId'
      preLoaderRoute: typeof DashboardBugsBugIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBugsBugIdRoute: typeof DashboardBugsBugIdRoute
  DashboardAccountsIndexRoute: typeof DashboardAccountsIndexRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
  DashboardBugsIndexRoute: typeof DashboardBugsIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBugsBugIdRoute: DashboardBugsBugIdRoute,
  DashboardAccountsIndexRoute: DashboardAccountsIndexRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
  DashboardBugsIndexRoute: DashboardBugsIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
